# ------------------------------------------------
# Basic
# ------------------------------------------------

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'taku-o/vim-toggle'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'itchyny/vim-gitbranch'


# ------------------------------------------------
# for Markdown
# ------------------------------------------------
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'


# ------------------------------------------------
# for Python
# ------------------------------------------------
[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'vim-scripts/Flake8-vim'

# ------------------------------------------------
# for TypeScript
# ------------------------------------------------
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'
