# ------------------------------------------------
# Basic
# ------------------------------------------------

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'taku-o/vim-toggle'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'lambdalisue/fern.vim'

